

# 5 Useful NumPy functions


### I have chosen the following 5 functions-

Numpy stands for Numerical Python. Numpy is an open source library which is used for numerical operations with respect to linear algebra and matrices. It is created by Travis Oliphant in 2005. 

- function 1 = np.split()
- function 2 = np.unique()
- function 3 = np.transpose()
- function 4 = np.maximum()
- function 5 = np.sort()



In [3]:
!pip install jovian --upgrade -q

In [8]:
import jovian

In [9]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: ········
[jovian] Updating notebook "ankit114211/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/ankit114211/numpy-array-operations


'https://jovian.ml/ankit114211/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [2]:
import numpy as np

In [7]:
# List of functions explained 
function1 = np.split
function2 = np.unique
function3 = np.transpose
function4 = np.full
function5 = np.sort

## Function 1 - np.split()
Split an array into multiple sub-arrays as views.

In [8]:
# Example 1 - working 
arr1 = np.array([1,2,3,4,5,6])
np.split(arr1,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

The second argument of np.split specifies into how many subarrays we want to divide the original array.

In [9]:
# Example 2 - working
arr2=np.array([5,33,2,15,2,0,4,3])
np.split(arr2,2)

[array([ 5, 33,  2, 15]), array([2, 0, 4, 3])]

In the above example I divided the array into 2 subarrays. Keep in mind it doesn't effect the original array.

In [10]:
# Example 3 - breaking (to illustrate when it breaks)
arr3 = np.array([1,2,3,4])
np.split(arr3,3)

ValueError: array split does not result in an equal division

Snap! what happened here? Because `np.split` divides the array into two subarrays but those subarrays should contain equal no of elements. If it is not possible to divide the original array into such subarrays it will throw an error. In the above example it is not possible to divide [1,2,3,4] into 3 parts with each part containing equal number of elements "ValueError: array split does not result in an equal division"

This function is useful when we want to divide the array into subarrays.

In [ ]:
jovian.commit()

## Function 2 - np.unique()

Returns the sorted unique elements of an array.

In [16]:
# Example 1 - working
arr1 = np.array([1,2,4,5,8,4,7,6])
np.unique(arr1)

array([1, 2, 4, 5, 6, 7, 8])

The function returns an array containing only the unique elements.

In [17]:
# Example 2 - working
arr2=np.array(['a','g','d','a','c'])
np.unique(arr2)

array(['a', 'c', 'd', 'g'], dtype='<U1')

This function is useful when we want only the unique elements in an array.

In [18]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
np.unique(a, axis=3)

AxisError: axis 3 is out of bounds for array of dimension 2

Since it is an 2-D array, the axis 3 is out of range.

This np.unique() fucntion can be used to get the unique values in an array.

In [19]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ankit114211/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/ankit114211/numpy-array-operations


'https://jovian.ml/ankit114211/numpy-array-operations'

## Function 3 - np.transpose()

For an array a with two axes, transpose(a) gives the matrix transpose.

In [11]:
# Example 1 - working
a=np.array([
    [1,2],
    [3,4]
])
np.transpose(a)

array([[1, 3],
       [2, 4]])

Simple matrix transpose

In [12]:
# Example 2 - working
a2=np.array([1,2,3])
np.transpose(a2)

array([1, 2, 3])

Transposing a 1-D array returns an unchanged view of the original array.

Use this function to calculate the transpose of a matrix.

In [20]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ankit114211/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/ankit114211/numpy-array-operations


'https://jovian.ml/ankit114211/numpy-array-operations'

## Function 4 - np.maximum

Compares two arrays and pulls the maximum value in each.

In [4]:
# Example 1 - working
ar1 = np.array([[74, 52, 44, 87], 
                 [19, 22, 95, 50], 
                 [16, 13, 7, 40]])

ar2 = np.array([[14, 66, 27, 74], 
                 [92, 2, 56, 49], 
                 [3, 11, 17, 99]])

np.maximum(ar1, ar2)

array([[74, 66, 44, 87],
       [92, 22, 95, 50],
       [16, 13, 17, 99]])

Compares two arrays of numbers, and brings back the highest numer in each creating one array with the highest ones.

In [5]:
# Example 2 - working
ar3 = np.array([[.24, .3, -.14, .67], 
                 [.87, .26, -.35, .21], 
                 [0, -.87, .36, .44]])

ar4 = np.array([[.21, .67, -.31, -.74], 
                 [.99, .52, -.56, .47], 
                 [-.87, -.23, .11, .5]])

np.maximum(ar3, ar4)


array([[ 0.24,  0.67, -0.14,  0.67],
       [ 0.99,  0.52, -0.35,  0.47],
       [ 0.  , -0.23,  0.36,  0.5 ]])

using decimals and negative numbers, pulls largest numbers again out of the pairs in the arrays.

In [6]:
# Example 3 - breaking (to illustrate when it breaks)
ar5 = np.array([["JOE", 52, 44, 87], 
                 [19, 22, 95, 50], 
                 [16, 13, 7, 40]])

ar6 = np.array([[14, 66, 27, 74], 
                 [92, 2, 56, 49], 
                 [3, 11, 17, 99]])

np.maximum(ar5, ar6)

UFuncTypeError: ufunc 'maximum' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')

"Joe" is not a number and cannot be calculated with np.maximum. Everything else stops with the error.

In [10]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ankit114211/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/ankit114211/numpy-array-operations


'https://jovian.ml/ankit114211/numpy-array-operations'

## Function 5 - np.sort()

Sorting means putting something in a sequence. Numpy comes with an inbuilt library which will allows us to sort an arrray in ascending order and retrurn us a copy of sorted array without modifying the actual instance.

In [11]:
# Example 1 - working
arr = np.array([[7,1],[5,9],[8,3]])
print('Along with the last axis :')
print(np.sort(arr))
print('Along with the first axis :')
print(np.sort(arr,axis=0))

Along with the last axis :
[[1 7]
 [5 9]
 [3 8]]
Along with the first axis :
[[5 1]
 [7 3]
 [8 9]]


In this example the print statement will return the sorted version of an array (arr) along with the default axis and along with the first axis.

In [12]:
# Example 2 - working
arr = np.array(['banana', 'cherry', 'apple','Mango'])
print('Ascending order :')
print(np.sort(arr))

Ascending order :
['Mango' 'apple' 'banana' 'cherry']


In this example we are sorting an array alphabatically. Here it captures the binary value of the first element to sort so you can see in the above example 'Mango' is the first element to be sorted.


In [13]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.array([[7,1],[5,9],[8,3]])
print(np.sort(arr,axis=2))

AxisError: axis 2 is out of bounds for array of dimension 2

In this example we have specified the wrong axis so it breaks It can be fixed by either continuing with default axis or giving the axis as 0 or 1.

In [14]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ankit114211/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/ankit114211/numpy-array-operations


'https://jovian.ml/ankit114211/numpy-array-operations'

## Conclusion

In this notebook you will find 5 useful numpy functions and 3 refrenced examples of every function. Out of the 3 one example will also convey you when the function is going to break so keep that condition in your mind while using those functions.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Used GeeksforGeeks for some extra refrence :https://www.geeksforgeeks.org/

In [21]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ankit114211/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/ankit114211/numpy-array-operations


'https://jovian.ml/ankit114211/numpy-array-operations'